<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

<?php $produit = Mage::registry('product'); ?>
<?php $associatedProducts = Mage::registry('associatedProducts'); ?>
<?php $helper = Mage::helper('product_blood'); ?>
<?php if(isset($produit)) :?>

<div class="wrapper row">
    <div class="preview col-md-6">

        <div class="preview-pic tab-content">
            <div class="tab-pane active" id="pic-1"><img style="height:400px;width:400px;" src="<?php echo $helper->getImageUrl($produit->getImageUrl()); ?>" /></div>
        </div>

    </div>
    <div class="details col-md-6">
        <h3 class="product-title"><?php echo $produit->getName() ?></h3>
        <div class="rating">
            <div class="stars">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
            </div>
            <span class="review-no">41 reviews</span>
        </div>
        <p class="product-description"><?php echo $produit->getDescription() ?></p>
        <p class="product-description">Tout nos produits sont certifiés Bio, traité dans les plus grands laboratoires. Prélevé directement sur des donneurs conssentant présentant pas ou peu de maladie infectueuses.</p>
        <h4 class="price">current price: <span><?php echo $produit->getPrice() ?>€</span></h4>
        <div class="action">
            <a href="<?php echo $this->helper('checkout/cart')->getAddUrl($produit) ?>"><button class="add-to-cart btn btn-default" type="button">add to cart</button></a>
        </div>
    </div>
</div>

<div class="block block-related">
    <div class="block-title">
        <h2><?php echo $this->__('Produits associés') ?></h2>
    </div>
    <div class="block-content">
        <p class="block-subtitle"><?php echo $this->__('Cocher des produits à ajouter au panier ou') ?>&nbsp;<a href="#" onclick="selectAllRelated(this); return false;"><?php echo $this->__('sélectionner tous') ?></a></p>
        <ol class="mini-products-list" id="block-related">
            <?php foreach($associatedProducts as $_item): ?>
                <li class="item">
                    <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
                        <?php if (!$_item->getRequiredOptions()): ?>
                            <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
                        <?php endif; ?>
                    <?php endif; ?>
                    <div class="product">
                        <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" class="product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($_item, 'image')->resize(75) ?>" width="75" height="75" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" />
                        </a>
                        <div class="product-details">
                            <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></p>
                            <?php echo number_format((float)$_item->getPrice(), 2, '.', '') ?>€
                            <br>
                            <a href="<?php echo $this->helper('checkout/cart')->getAddUrl($_item) ?>"><button type="button" class="btn-primary"><?php echo $this->__('Add to Cart') ?></button></a>
                        </div>
                    </div>
                </li>
            <?php endforeach ?>
        </ol>
        <script type="text/javascript">decorateList('block-related', 'none-recursive')</script>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        $$('.related-checkbox').each(function(elem){
            Event.observe(elem, 'click', addRelatedToProduct)
        });

        var relatedProductsCheckFlag = false;
        function selectAllRelated(txt){
            if (relatedProductsCheckFlag == false) {
                $$('.related-checkbox').each(function(elem){
                    elem.checked = true;
                });
                relatedProductsCheckFlag = true;
                txt.innerHTML="<?php echo Mage::helper('core')->jsQuoteEscape($this->__('unselect all')) ?>";
            } else {
                $$('.related-checkbox').each(function(elem){
                    elem.checked = false;
                });
                relatedProductsCheckFlag = false;
                txt.innerHTML="<?php echo Mage::helper('core')->jsQuoteEscape($this->__('select all')) ?>";
            }
            addRelatedToProduct();
        }

        function addRelatedToProduct(){
            var checkboxes = $$('.related-checkbox');
            var values = [];
            for(var i=0;i<checkboxes.length;i++){
                if(checkboxes[i].checked) values.push(checkboxes[i].value);
            }
            if($('related-products-field')){
                $('related-products-field').value = values.join(',');
            }
        }
        //]]>
    </script>
</div>
<?php endif; ?>