<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

<?php $produit = Mage::registry('product'); ?>
<?php $helper = Mage::helper('product_blood'); ?>
<?php if(isset($produit)) :?>

<div class="wrapper row">
    <div class="preview col-md-6">

        <div class="preview-pic tab-content">
            <div class="tab-pane active" id="pic-1"><img style="height:400px;width:400px;" src="<?php echo $helper->getImageUrl($produit->getImageUrl()); ?>" /></div>
        </div>

    </div>
    <div class="details col-md-6">
        <h3 class="product-title"><?php echo $produit->getName() ?></h3>
        <div class="rating">
            <div class="stars">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
            </div>
            <span class="review-no">41 reviews</span>
        </div>
        <p class="product-description"><?php echo $produit->getDescription() ?></p>
        <p class="product-description">Tout nos produits sont certifiés Bio, traité dans les plus grands laboratoires. Prélevé directement sur des donneurs conssentant présentant pas ou peu de maladie infectueuses.</p>
        <h4 class="price">current price: <span><?php echo $produit->getPrice() ?>€</span></h4>
        <div class="action">
            <button class="add-to-cart btn btn-default" type="button">add to cart</button>
        </div>
    </div>
</div>

<?php endif; ?>